FROM usgseros/ubuntu-gis-py
MAINTAINER USGS LCMAP http://eros.usgs.gov

RUN apt-get update
RUN apt-get install -y python3-nose python3-click python3-requests
RUN apt-get install -y python3-termcolor python3-dateutil
RUN apt-get install -y python3-pandas python3-zope.interface python3-tz
RUN curl -O https://bootstrap.pypa.io/get-pip.py
RUN python3 get-pip.py
RUN pip install git+https://github.com/usgs-eros/lcmap-client-py
RUN apt-get install -y libgsl0-dev libgsl0ldbl gsl-bin \
    libmatio-dev libmatio2 gfortran

RUN useradd -ms /bin/bash science
USER    science
WORKDIR /home/science
RUN mkdir -p /home/science/lib

# set env vars
ENV CCDC_BIN /home/science/lib
ENV LD_LIBRARY_PATH /home/science/lib

# comment this out if you aren't developing the c code
RUN echo "DEVELOP_MODE_FLAG"
# end c develop mode

RUN git clone https://github.com/USGS-EROS/lcmap-change-detection-c.git
RUN cd lcmap-change-detection-c && git checkout topic/c-function-type && \
    BIN=$CCDC_BIN make

COPY    science /home/science
RUN ln -s /home/science/lcmap-change-detection-c/ccdc/the_ccd.so /home/science/lib/
ENTRYPOINT ["/usr/bin/python3", "cli.py"]
